/**
 * `.dev.vars` — the local runtime env for `wrangler dev`, generated whole.
 *
 * The file is a materialization, never a source: platform-derived values
 * (JWTs, worker URLs) plus a cached copy of the app's secret store, rewritten
 * on every dev, test, deploy, and `secrets pull` run. Nothing reads it back,
 * and hand edits do not survive the next write — a value the app needs lives
 * in the store (`npx deepspace secrets set`), which is also the only thing a
 * deploy ships.
 *
 * It used to be three zones: an SDK section, a hand-edited section preserved
 * across writes, and the store cache — which required a divider grammar, a
 * dotenv parser to read the file back, and a deploy guard reconciling the two
 * sources (docs/proposals/secrets-source-of-truth.md). One source of truth
 * deleted all of it.
 */

import { PLATFORM_URLS } from '../env'
import { readAppId } from './app-identity'
import { fetchAppIdentityToken, fetchPublicKey, mintAppOwnerJwt } from './app-tokens'
import { writeSecretFileSync } from './secure-file'
import { devVarsPathFor } from './wrangler-env'

interface WriteDevVarsOptions {
  appId?: string
  /** Rendered store-secrets block (`renderSecretsCache`). */
  generatedSecretsCache?: string
}

const HEADER = [
  '# Generated by deepspace — do not edit; this file is rewritten on every',
  '# dev, test, deploy, and secrets pull run. App values live in the secret store:',
  '#   npx deepspace secrets set KEY=value',
].join('\n')

function requireAppIdFor(appDir: string, wranglerEnv?: string): string {
  const id = readAppId(appDir, wranglerEnv)
  if (id) return id
  throw new Error(
    'wrangler.toml has no DEEPSPACE_APP_ID' +
      (wranglerEnv ? ` for [env.${wranglerEnv}]` : '') +
      '. Run `deepspace app init` (or `deepspace app init --env <name>`) and retry.',
  )
}

/** Write the whole file from platform truth + the store cache. */
export async function writeDevVars(
  appDir: string,
  ownerId: string,
  callerJwt: string,
  wranglerEnv?: string,
  opts: WriteDevVarsOptions = {},
): Promise<void> {
  const urls = PLATFORM_URLS
  const publicKey = await fetchPublicKey(urls.auth)
  const appId = opts.appId ?? requireAppIdFor(appDir, wranglerEnv)
  const appOwnerJwt = await mintAppOwnerJwt(urls.auth, callerJwt, appId)
  const appIdentityToken = await fetchAppIdentityToken(urls.deploy, callerJwt, appId)

  // Wrangler requires quotes around multi-line PEM values. ALLOW_DEBUG_ROUTES
  // is dev-only here: deploys ship the store, so this value never reaches
  // production — a store entry for the same key lands later in the file and
  // wins locally too (dotenv last-write).
  const sdkVars = [
    `AUTH_JWT_PUBLIC_KEY="${publicKey}"`,
    `AUTH_JWT_ISSUER=${urls.auth}/api/auth`,
    `AUTH_WORKER_URL=${urls.auth}`,
    `API_WORKER_URL=${urls.api}`,
    `PLATFORM_WORKER_URL=${urls.platform}`,
    `OWNER_USER_ID=${ownerId}`,
    `APP_OWNER_JWT=${appOwnerJwt}`,
    ...(appIdentityToken ? [`APP_IDENTITY_TOKEN=${appIdentityToken}`] : []),
    `ALLOW_DEBUG_ROUTES=true`,
  ].join('\n')

  const devVarsPath = devVarsPathFor(appDir)
  const cache = opts.generatedSecretsCache
  writeSecretFileSync(
    devVarsPath,
    [HEADER, '', sdkVars, ...(cache ? ['', cache] : []), ''].join('\n'),
  )
}
