/**
 * `.dev.vars` is generated whole. Nothing is read back; nothing survives.
 */

import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'

vi.mock('../app-tokens', () => ({
  fetchPublicKey: vi.fn(async () => '-----BEGIN PUBLIC KEY-----\nPK\n-----END PUBLIC KEY-----'),
  mintAppOwnerJwt: vi.fn(async () => 'owner-jwt'),
  fetchAppIdentityToken: vi.fn(async () => 'identity-token'),
}))

import { writeDevVars } from '../dev-vars'
import { renderSecretsCache } from '../secrets'

const APP_ID = 'app_01HZXYABCDEFGHJKMNPQRSTVWX'

let dir: string | undefined
afterEach(() => {
  if (dir) rmSync(dir, { recursive: true, force: true })
  dir = undefined
})

describe('writeDevVars', () => {
  it('generates the whole file: header, SDK section, store block', async () => {
    dir = mkdtempSync(join(tmpdir(), 'ds-devvars-'))
    await writeDevVars(dir, 'user-1', 'caller-jwt', undefined, {
      appId: APP_ID,
      generatedSecretsCache: renderSecretsCache(
        { API_KEY: 'v1' },
        { appId: APP_ID, configName: 'prd' },
      ),
    })

    const body = readFileSync(join(dir, '.dev.vars'), 'utf-8')
    expect(body).toContain('# Generated by deepspace — do not edit')
    expect(body).toContain('# dev, test, deploy, and secrets pull run.')
    // Multi-line PEM stays quoted (wrangler requires it).
    expect(body).toContain(
      'AUTH_JWT_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nPK\n-----END PUBLIC KEY-----"',
    )
    expect(body).toContain('APP_OWNER_JWT=owner-jwt')
    expect(body).toContain('APP_IDENTITY_TOKEN=identity-token')
    // The store block, after the SDK section so a store value wins locally.
    expect(body).toContain(`# App secrets · config prd · app ${APP_ID}`)
    expect(body).toContain('API_KEY=v1')
  })

  it('does not preserve hand edits — the file is a materialization, not a source', async () => {
    // The old three-zone writer kept lines below a divider across runs, which
    // made the file a second source of truth and a de-facto deploy input
    // (docs/proposals/secrets-source-of-truth.md). A hand-added value must now
    // vanish on the next write: the store is the only place values live.
    dir = mkdtempSync(join(tmpdir(), 'ds-devvars-'))
    const path = join(dir, '.dev.vars')
    writeFileSync(
      path,
      [
        'MY_TOKEN=hand-edited',
        '# --- not managed by the SDK; preserved across dev/test runs ---',
        'KEEP=me',
      ].join('\n'),
    )

    await writeDevVars(dir, 'user-1', 'caller-jwt', undefined, { appId: APP_ID })

    const body = readFileSync(path, 'utf-8')
    expect(body).not.toContain('MY_TOKEN')
    expect(body).not.toContain('KEEP=me')
    expect(body).not.toContain('preserved across')
  })

  it('uses the one generated .dev.vars file for named environments', async () => {
    dir = mkdtempSync(join(tmpdir(), 'ds-devvars-'))
    await writeDevVars(dir, 'user-1', 'caller-jwt', 'staging', {
      appId: APP_ID,
    })
    expect(existsSync(join(dir, '.dev.vars'))).toBe(true)
    expect(existsSync(join(dir, '.dev.vars.staging'))).toBe(false)
  })
})
